config/routes.rb
Spree::Core::Engine.routes.draw do
  # For focas payment method.
  post '/orders/:order_id/checkout/focas_notify/:payment_method_id', to: 'checkout#focas_notify', as: :focas_notify_order_checkout  #, constraints: { protocol: 'https' }
  get 'redirect_to_focas/:id.:payment_method_id', to: 'checkout#redirect_to_focas', as: :redirect_to_focas
end

app/models/spree/billing_integration/focas.rb
class Spree::BillingIntegration::Focas < Spree::BillingIntegration
  preference :merchant_id, :string
  preference :mer_id,      :string
  preference :terminal_id, :string

  def provider_class
    ActiveMerchant::Billing::Integrations::Focas
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spree/checkout_controller_decorator.rb
module Spree
  CheckoutController.class_eval do

    # prevent the ActionController::InvalidAuthenticityToken error
    protect_from_forgery except: :focas_notify  

    def focas_notify
      notification = ActiveMerchant::Billing::Integrations::Focas::Notification.new(request.raw_post)

      puts notification.inspect

      @order = Spree::Order.find_by_id(params[:order_id])
  
      if notification.complete?
        # payment is compeleted
        payment_method = Spree::PaymentMethod.find_by_id(params[:payment_method_id])
        payment = @order.payments.create({ amount: @order.total,                                            
                                           payment_method: payment_method})
        payment.started_processing!
        payment.complete!

        @order.update_attributes({ state: "complete", completed_at: Time.now, payment_total: @order.total })

        until @order.state == "complete"
          if @order.next!
            @order.update!
            state_callback(:after)
          end
        end
  
        @order.finalize!
  
        flash.notice = Spree.t(:order_processed_successfully) + ", no:#{notification.lidm}"
        redirect_to orders_path
      else
        # payment is failed
        flash[:error] = Spree.t(:payment_has_been_cancelled) + " status:#{notification.status}, errcode:#{notification.errcode}"
        redirect_to edit_order_path(@order)
      end
  
      puts '1|OK,  status: 200'
    end

    def redirect_to_focas
      @order = Spree::Order.find_by_id(params[:id])
      @payment_method_id = params[:payment_method_id]
      @preferences = Spree::PaymentMethod.find_by_id(params[:payment_method_id]).preferences
      if @preferences[:merchant_id].empty? || @preferences[:mer_id].empty? || @preferences[:terminal_id].empty?
        flash[:error] = Spree.t(:focas_parameters_are_not_set)
        redirect_to :back
        return
      end  
      render layout: false
    end
  end
end

app/views/spree/admin/payments/source_forms/_focas.html.erb
<% content_for :head do %>
  <script type="text/javascript">
    jQuery(document).ready(function(){
      $("label:contains('<%= payment_method.name %>')").hide();
      $("label:contains('<%= payment_method.name %>') input").disable();
    });
  </script>
<% end %>

app/views/spree/admin/payments/source_views/_focas.html.erb
<fieldset>
  <legend><%= Spree.t(:focas) %></legend>

  <table class="index">
    <tr>
      <th colspan="6"><%= Spree.t(:focas) %></th>
    </tr>
    <tr>
      <td><label><%= Spree.t(:amount) %>:</label></td>
      <td>
        <%= payment.amount %>
      </td>
    </tr>
  </table>
</fieldset>

app/views/spree/checkout/payment/_focas.html.erb
<%= "#{Spree.t(:payment_method)}: #{payment_method.method_type}" %><br />
<%= "#{Spree.t(:order_number)}: #{@order.number}" %><br />
<%= "#{Spree.t(:amount)}: #{@order.total.to_i.to_s} #{@order.currency}" %><br /><br />
<%= link_to Spree.t(:forward_to_credit_card_payment), redirect_to_focas_path(@order.id, payment_method.id), class: 'button' %>

app/views/spree/checkout/redirect_to_focas.html.erb
<% payment_service_for @order.number,
                      @preferences[:merchant_id],
                      service: :focas,
                      html: { id: 'focas-form', method: :post } do |service| %>
  <% service.lidm @order.number %>
  <% service.amount @order.total.to_i.to_s %>
  <% service.mer_id @preferences[:mer_id] %>
  <% service.terminal_id @preferences[:terminal_id] %> 
  <% service.local_date Time.now %>
  <% service.local_time Time.now %>
  <% service.client_back_url order_checkout_url(@order.id) %>
  <% service.notify_url focas_notify_order_checkout_url(@order.id, payment_method_id: @payment_method_id) if Rails.env.production? %>
  <% service.notify_url "https://127.0.0.1:3001/orders/#{@order.id}/checkout/focas_notify/#{@payment_method_id}" if Rails.env.development? %>
  <%= submit_tag Spree.t(:press_to_process), class: 'button' %>
<% end %>